// Generated by gencpp from file test_msg/vehicle_ctrl.msg
// DO NOT EDIT!


#ifndef TEST_MSG_MESSAGE_VEHICLE_CTRL_H
#define TEST_MSG_MESSAGE_VEHICLE_CTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_msg
{
template <class ContainerAllocator>
struct vehicle_ctrl_
{
  typedef vehicle_ctrl_<ContainerAllocator> Type;

  vehicle_ctrl_()
    : speed(0.0)
    , accspeed(0.0)
    , angle(0.0)  {
    }
  vehicle_ctrl_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , accspeed(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef float _accspeed_type;
  _accspeed_type accspeed;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::test_msg::vehicle_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_msg::vehicle_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct vehicle_ctrl_

typedef ::test_msg::vehicle_ctrl_<std::allocator<void> > vehicle_ctrl;

typedef boost::shared_ptr< ::test_msg::vehicle_ctrl > vehicle_ctrlPtr;
typedef boost::shared_ptr< ::test_msg::vehicle_ctrl const> vehicle_ctrlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_msg::vehicle_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_msg::vehicle_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'test_msg': ['/home/lhospital/MyProgramm/AutoDrive_Arduino/Ros/catkin_ws/src/test_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_msg::vehicle_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msg::vehicle_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msg::vehicle_ctrl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb7f1353bf56e905646c8a5e041d332d";
  }

  static const char* value(const ::test_msg::vehicle_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb7f1353bf56e905ULL;
  static const uint64_t static_value2 = 0x646c8a5e041d332dULL;
};

template<class ContainerAllocator>
struct DataType< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_msg/vehicle_ctrl";
  }

  static const char* value(const ::test_msg::vehicle_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n\
float32 accspeed\n\
float32 angle\n\
";
  }

  static const char* value(const ::test_msg::vehicle_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.accspeed);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehicle_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_msg::vehicle_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_msg::vehicle_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "accspeed: ";
    Printer<float>::stream(s, indent + "  ", v.accspeed);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MSG_MESSAGE_VEHICLE_CTRL_H
